eureka:
  client:
    serviceUrl:
      defaultZone: http://192.168.10.16:8061/eureka/
  instance:
    preferIpAddress: true
spring:
  sleuth:
    enabled: true
    baggage:
      remoteFields: Correlation-Id
      correlationFields: Correlation-Id
  zipkin:
    enabled: true
  cloud:
    loadbalancer:
      ribbon:
        enabled: false