eureka:
  client:
    serviceUrl:
      defaultZone: http://192.168.10.16:18060/eureka/,http://192.168.9.224:18060/eureka/
  instance:
    preferIpAddress: true
spring:
  cloud:
    loadbalancer:
      ribbon:
        enabled: false