server:
  port: 8060

eureka:
  client:
    serviceUrl:
      defaultZone: http://192.168.10.16:8061/eureka/

spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
      - id: deepsignal-adapter
        uri: lb://deepsignal-adapter
        predicates:
        - Path=/deepsignal-adapter/**
        filters:
        - RewritePath=/deepsignal-adapter/(?<path>.*), /$\{path}
      - id: deepsignal-web
        uri: lb://deepsignal-web
        predicates:
        - Path=/deepsignal-web/**
        filters:
        - RewritePath=/deepsignal-web/(?<path>.*), /$\{path}
      - id: openapi
        uri: http://localhost:${server.port}
        predicates:
        - Path=/v3/api-docs/**
        filters:
        - RewritePath=/v3/api-docs/(?<path>.*), /$\{path}/v3/api-docs

springdoc:
  swagger-ui:
    urls:
      - name: deepsignal-web
        url: /v3/api-docs/deepsignal-web
      - name: deepsignal-adapter
        url: /v3/api-docs/deepsignal-adapter
application: gateway2
