spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
      - id: deepsignal-adapter
        uri: lb://deepsignal-adapter
        predicates:
        - Path=/deepsignal-adapter/**
        filters:
        - RewritePath=/deepsignal-adapter/(?<path>.*), /$\{path}
      - id: deepsignal-web
        uri: lb://deepsignal-web
        predicates:
        - Path=/deepsignal-web/**
        filters:
        - RewritePath=/deepsignal-web/(?<path>.*), /$\{path}
      - id: deepsignal-feed-cache
        uri: lb://deepsignal-feed-cache
        predicates:
        - Path=/deepsignal-feed-cache/**
        filters:
        - RewritePath=/deepsignal-feed-cache/(?<path>.*), /$\{path}
      - id: openapi
        uri: http://localhost:${server.port}
        predicates:
          - Path=/v3/api-docs/**
        filters:
          - RewritePath=/v3/api-docs/(?<path>.*), /$\{path}/v3/api-docs
      - id: feignclient
        uri: lb://feignclient
        predicates:
          - Path=/feignclient/**
        filters:
          - RewritePath=/feignclient/(?<path>.*), /feignclient/$\{path}
      - id: eurekaclient-service
        uri: lb://eurekaclient-service
        predicates:
          - Path=/eurekaclient-service/**
        filters:
          - RewritePath=/eurekaclient-service/(?<path>.*), /eurekaclient-service/$\{path}
          # - RewritePath=/eurekaclient-service/(?<path>.*), /$\{path}
          - RewritePath=/eurekaclient-service/v3/(?<path>.*), /v3/$\{path}
          # - RewritePath=/v3/api-docs/(?<path>.*), /$\{path}/v3/api-docs
          - RewritePath=/eurekaclient-service/testx, /eurekaclient-service/test2
      

springdoc:
  swagger-ui:
    urls:
      - name: deepsignal-web
        url: /v3/api-docs/deepsignal-web
      - name: deepsignal-adapter
        url: /v3/api-docs/deepsignal-adapter
      - name: deepsignal-feed-cache
        url: /v3/api-docs/deepsignal-feed-cache
      - name: eurekaclient-service
        url: /v3/api-docs/eurekaclient-service
      - name: feignclient
        url: /v3/api-docs/feignclient

server:
  port: 18300

eureka:
  instance:
    prefer-ip-address: true
  client:
    serviceUrl:
      defaultZone: http://192.168.10.16:18060/eureka/,http://192.168.9.224:18060/eureka/

management:

  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    gateway:
      enabled: true # default: true

# management:
#   endpoint:
#     shutdown:
#       enabled: true
#   endpoints:
#     web:
#       exposure:
#         include: "*"

logging:
  level:
    ROOT: INFO
    com.saltlux.deepsignal: INFO

gooverauth:
  secret: goover.ai
  expiration_minute: 1440   #1440(1day)=60minute*24
  withsubject: gooverServiceAuth
  
